"""Updated VacancyModel

Revision ID: 80af47a37c3f
Revises: cad116299ec9
Create Date: 2026-03-18 01:31:39.940368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80af47a37c3f'
down_revision: Union[str, Sequence[str], None] = 'cad116299ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('minimal_salary', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('minimal_year_exp', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('job_location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'job_location')
    op.drop_column('vacancies', 'minimal_year_exp')
    op.drop_column('vacancies', 'minimal_salary')
    # ### end Alembic commands ###
