"""Job application table modified

Revision ID: ded184b0472e
Revises: 8add250abd70
Create Date: 2026-03-23 01:39:21.479156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded184b0472e'
down_revision: Union[str, Sequence[str], None] = '8add250abd70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('cancelled', sa.Boolean(), nullable=False))
    op.alter_column('job_applications', 'cover_letter',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('job_applications', 'accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('job_applications', 'rejected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('rejected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('job_applications', 'accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('job_applications', 'cover_letter',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('job_applications', 'cancelled')
    # ### end Alembic commands ###
